# Generated by Django 5.0.1 on 2024-03-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='date',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='location',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='names',
        ),
        migrations.AddField(
            model_name='weather',
            name='current_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='rainfall',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='sky',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
    ]
