# Generated by Django 5.0.1 on 2024-03-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='temp',
            new_name='temperature',
        ),
    ]
