# Generated by Django 5.0.1 on 2024-03-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0002_rename_temp_weather_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='user',
        ),
    ]
