# Generated by Django 5.0.1 on 2024-03-05 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0003_remove_weather_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rain_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='sky',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
