# Generated by Django 5.0.1 on 2024-02-06 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('recommend_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend', to='recommends.recommend')),
            ],
        ),
    ]
